# Generated by Django 4.0.4 on 2022-06-20 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('familiaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='id',
            field=models.CharField(default=uuid.UUID('b2b79683-d2e5-4c28-a35d-85241eeb1fb3'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menues',
            name='id',
            field=models.CharField(default=uuid.UUID('16692cfe-1601-4f91-9756-b1385e0f54ef'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
